name: pushwoosh_geozones
description: This plugin enables Pushwoosh Geozones feature.
version: 2.2.26
author: Pushwoosh <support@pushwoosh.com>
homepage: https://www.pushwoosh.com/v1.0/docs/geozones

dependencies:
  flutter:
    sdk: flutter
  pushwoosh_flutter: 
    path: ../pushwoosh

environment:
  sdk: '>=2.12.0 <3.0.0'

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.pushwoosh.pushwooshgeozones
    pluginClass: PushwooshGeozonesPlugin

